"""
This type stub file was generated by pyright.
"""

from . import _version

"""Pillow (Fork of the Python Imaging Library)

Pillow is the friendly PIL fork by Alex Clark and Contributors.
    https://github.com/python-pillow/Pillow/

Pillow is forked from PIL 1.1.7.

PIL is the Python Imaging Library by Fredrik Lundh and Contributors.
Copyright (c) 1999 by Secret Labs AB.

Use PIL.__version__ for this Pillow version.

;-)
"""
__version__ = _version.__version__
_plugins = ["BlpImagePlugin", "BmpImagePlugin", "BufrStubImagePlugin", "CurImagePlugin", "DcxImagePlugin", "DdsImagePlugin", "EpsImagePlugin", "FitsStubImagePlugin", "FliImagePlugin", "FpxImagePlugin", "FtexImagePlugin", "GbrImagePlugin", "GifImagePlugin", "GribStubImagePlugin", "Hdf5StubImagePlugin", "IcnsImagePlugin", "IcoImagePlugin", "ImImagePlugin", "ImtImagePlugin", "IptcImagePlugin", "JpegImagePlugin", "Jpeg2KImagePlugin", "McIdasImagePlugin", "MicImagePlugin", "MpegImagePlugin", "MpoImagePlugin", "MspImagePlugin", "PalmImagePlugin", "PcdImagePlugin", "PcxImagePlugin", "PdfImagePlugin", "PixarImagePlugin", "PngImagePlugin", "PpmImagePlugin", "PsdImagePlugin", "SgiImagePlugin", "SpiderImagePlugin", "SunImagePlugin", "TgaImagePlugin", "TiffImagePlugin", "WebPImagePlugin", "WmfImagePlugin", "XbmImagePlugin", "XpmImagePlugin", "XVThumbImagePlugin"]
class UnidentifiedImageError(IOError):
    ...


