"""
This type stub file was generated by pyright.
"""

import sys
from tkinter import _tkinter as tk

""" Find compiled module linking to Tcl / Tk libraries
"""
if hasattr(sys, "pypy_find_executable"):
    ...
else:
    TKINTER_LIB = tk.__file__
