"""
This type stub file was generated by pyright.
"""

import sys

py36 = sys.version_info[0: 2] >= (3, 6)
if py36:
    def isPath(f):
        ...
    
else:
    def isPath(f):
        ...
    
def isDirectory(f):
    ...

class deferred_error:
    def __init__(self, ex):
        self.ex = ...
    
    def __getattr__(self, elt):
        ...
    


