"""
This type stub file was generated by pyright.
"""

from . import ImageFile

BIT2MODE = { 1: ("P", "P;1"),4: ("P", "P;4"),8: ("P", "P"),16: ("RGB", "BGR;15"),24: ("RGB", "BGR"),32: ("RGB", "BGRX") }
def _accept(prefix):
    ...

def _dib_accept(prefix):
    ...

class BmpImageFile(ImageFile.ImageFile):
    """ Image plugin for the Windows Bitmap format (BMP) """
    format_description = ...
    format = ...
    COMPRESSIONS = ...
    def _bitmap(self, header=..., offset=...):
        """ Read relevant info about the BMP """
        self.tile = ...
    
    def _open(self):
        """ Open file, check magic number and read header """
        ...
    


class DibImageFile(BmpImageFile):
    format = ...
    format_description = ...
    def _open(self):
        ...
    


SAVE = { "1": ("1", 1, 2),"L": ("L", 8, 256),"P": ("P", 8, 256),"RGB": ("BGR", 24, 0),"RGBA": ("BGRA", 32, 0) }
def _dib_save(im, fp, filename):
    ...

def _save(im, fp, filename, bitmap_header: bool = ...):
    ...

