"""
This type stub file was generated by pyright.
"""

from . import BmpImagePlugin

def _accept(prefix):
    ...

class CurImageFile(BmpImagePlugin.BmpImageFile):
    format = ...
    format_description = ...
    def _open(self):
        ...
    


