"""
This type stub file was generated by pyright.
"""

from .PcxImagePlugin import PcxImageFile

MAGIC = 987654321
def _accept(prefix):
    ...

class DcxImageFile(PcxImageFile):
    format = ...
    format_description = ...
    _close_exclusive_fp_after_loading = ...
    def _open(self):
        self.frame = ...
    
    @property
    def n_frames(self):
        ...
    
    @property
    def is_animated(self):
        ...
    
    def seek(self, frame):
        self.frame = ...
        self.fp = ...
    
    def tell(self):
        ...
    
    def _close__fp(self):
        ...
    


