"""
This type stub file was generated by pyright.
"""

from . import ImageFile

def _accept(prefix):
    ...

class GbrImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...
    def _open(self):
        ...
    
    def load(self):
        self.im = ...
    


