"""
This type stub file was generated by pyright.
"""

class GimpPaletteFile:
    rawmode = ...
    def __init__(self, fp):
        self.palette = ...
        self.palette = ...
    
    def getpalette(self):
        ...
    


