"""
This type stub file was generated by pyright.
"""

_modes = None
class ModeDescriptor:
    """Wrapper for mode strings."""
    def __init__(self, mode, bands, basemode, basetype):
        self.mode = ...
        self.bands = ...
        self.basemode = ...
        self.basetype = ...
    
    def __str__(self):
        ...
    


def getmode(mode):
    """Gets a mode descriptor for the given mode."""
    ...

