"""
This type stub file was generated by pyright.
"""

import re
from . import ImageFile

field = re.compile(rb"([a-z]*) ([^ \r\n]*)")
class ImtImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...
    def _open(self):
        ...
    


