"""
This type stub file was generated by pyright.
"""

from . import ImageFile

class BitStream:
    def __init__(self, fp):
        self.fp = ...
        self.bits = ...
        self.bitbuffer = ...
    
    def next(self):
        ...
    
    def peek(self, bits):
        ...
    
    def skip(self, bits):
        self.bits = ...
    
    def read(self, bits):
        self.bits = ...
    


class MpegImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...
    def _open(self):
        self.mode = ...
    


