"""
This type stub file was generated by pyright.
"""

from . import ImageFile

def _accept(prefix):
    ...

class MspImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...
    def _open(self):
        self.mode = ...
    


class MspDecoder(ImageFile.PyDecoder):
    _pulls_fd = ...
    def decode(self, buffer):
        ...
    


def _save(im, fp, filename):
    ...

