"""
This type stub file was generated by pyright.
"""

from . import FontFile

PCF_MAGIC = 1885562369
PCF_PROPERTIES = 1 << 0
PCF_ACCELERATORS = 1 << 1
PCF_METRICS = 1 << 2
PCF_BITMAPS = 1 << 3
PCF_INK_METRICS = 1 << 4
PCF_BDF_ENCODINGS = 1 << 5
PCF_SWIDTHS = 1 << 6
PCF_GLYPH_NAMES = 1 << 7
PCF_BDF_ACCELERATORS = 1 << 8
BYTES_PER_ROW = [lambda bits: bits + 7 >> 3, lambda bits: bits + 15 >> 3 & ~ 1, lambda bits: bits + 31 >> 3 & ~ 3, lambda bits: bits + 63 >> 3 & ~ 7]
def sz(s, o):
    ...

class PcfFontFile(FontFile.FontFile):
    name = ...
    def __init__(self, fp):
        self.toc = ...
        self.fp = ...
        self.info = ...
    
    def _getformat(self, tag):
        ...
    
    def _load_properties(self):
        ...
    
    def _load_metrics(self):
        ...
    
    def _load_bitmaps(self, metrics):
        ...
    
    def _load_encoding(self):
        ...
    


