"""
This type stub file was generated by pyright.
"""

from . import ImageFile

def _accept(prefix):
    ...

MODES = { (1, 1, 1): "L",(1, 2, 1): "L",(2, 1, 1): "L;16B",(2, 2, 1): "L;16B",(1, 3, 3): "RGB",(2, 3, 3): "RGB;16B",(1, 3, 4): "RGBA",(2, 3, 4): "RGBA;16B" }
class SgiImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...
    def _open(self):
        self.mode = ...
    


def _save(im, fp, filename):
    ...

class SGI16Decoder(ImageFile.PyDecoder):
    _pulls_fd = ...
    def decode(self, buffer):
        ...
    


