"""
This type stub file was generated by pyright.
"""

from . import ImageFile

def _accept(prefix):
    ...

class SunImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...
    def _open(self):
        ...
    


