"""
This type stub file was generated by pyright.
"""

from . import ImageFile

MODES = { (1, 8): "P",(3, 1): "1",(3, 8): "L",(3, 16): "LA",(2, 16): "BGR;5",(2, 24): "BGR",(2, 32): "BGRA" }
class TgaImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...
    def _open(self):
        ...
    


SAVE = { "1": ("1", 1, 0, 3),"L": ("L", 8, 0, 3),"LA": ("LA", 16, 0, 3),"P": ("P", 8, 1, 1),"RGB": ("BGR", 24, 0, 2),"RGBA": ("BGRA", 32, 0, 2) }
def _save(im, fp, filename):
    ...

