"""
This type stub file was generated by pyright.
"""

from . import Image, ImageFile
from typing import Any, Optional

_handler = None
def register_handler(handler):
    """
    Install application-specific WMF image handler.

    :param handler: Handler object.
    """
    ...

if hasattr(Image.core, "drawwmf"):
    class WmfHandler:
        def open(self, im):
            self.bbox = ...
        
        def load(self, im):
            ...
        
    
    
def _accept(prefix):
    ...

class WmfStubImageFile(ImageFile.StubImageFile):
    format = ...
    format_description = ...
    def _open(self):
        self.mode = ...
    
    def _load(self):
        ...
    
    def load(self, dpi: Optional[Any] = ...):
        ...
    


def _save(im, fp, filename):
    ...

