"""
This type stub file was generated by pyright.
"""

import re
from . import ImageFile

xbm_head = re.compile(rb"\s*#define[ \t]+.*_width[ \t]+(?P<width>[0-9]+)[\r\n]+" b"#define[ \t]+.*_height[ \t]+(?P<height>[0-9]+)[\r\n]+" b"(?P<hotspot>" b"#define[ \t]+[^_]*_x_hot[ \t]+(?P<xhot>[0-9]+)[\r\n]+" b"#define[ \t]+[^_]*_y_hot[ \t]+(?P<yhot>[0-9]+)[\r\n]+" b")?" b"[\\000-\\377]*_bits\\[\\]")
def _accept(prefix):
    ...

class XbmImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...
    def _open(self):
        ...
    


def _save(im, fp, filename):
    ...

