"""
This type stub file was generated by pyright.
"""

from . import ImageFile

_MAGIC = b"P7 332"
PALETTE = b""
def _accept(prefix):
    ...

class XVThumbImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...
    def _open(self):
        self.mode = ...
        self.palette = ...
        self.tile = ...
    


