"""
This type stub file was generated by pyright.
"""

from keras.applications import densenet
from . import Backbone
from typing import Any, Optional

"""
Copyright 2018 vidosits (https://github.com/vidosits/)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
allowed_backbones = { 'densenet121': ([6, 12, 24, 16], densenet.DenseNet121),'densenet169': ([6, 12, 32, 32], densenet.DenseNet169),'densenet201': ([6, 12, 48, 32], densenet.DenseNet201) }
class DenseNetBackbone(Backbone):
    """ Describes backbone information and provides utility functions.
    """
    def retinanet(self, *args, **kwargs):
        """ Returns a retinanet model using the correct backbone.
        """
        ...
    
    def download_imagenet(self):
        """ Download pre-trained weights for the specified backbone name.
        This name is in the format {backbone}_weights_tf_dim_ordering_tf_kernels_notop
        where backbone is the densenet + number of layers (e.g. densenet121).
        For more info check the explanation from the keras densenet script itself:
            https://github.com/keras-team/keras/blob/master/keras/applications/densenet.py
        """
        ...
    
    def validate(self):
        """ Checks whether the backbone string is correct.
        """
        ...
    
    def preprocess_image(self, inputs):
        """ Takes as input an image and prepares it for being passed through the network.
        """
        ...
    


def densenet_retinanet(num_classes, backbone=..., inputs: Optional[Any] = ..., modifier: Optional[Any] = ..., **kwargs):
    """ Constructs a retinanet model using a densenet backbone.

    Args
        num_classes: Number of classes to predict.
        backbone: Which backbone to use (one of ('densenet121', 'densenet169', 'densenet201')).
        inputs: The inputs to the network (defaults to a Tensor of shape (None, None, 3)).
        modifier: A function handler which can modify the backbone before using it in retinanet (this can be used to freeze backbone layers for example).

    Returns
        RetinaNet model with a DenseNet backbone.
    """
    ...

