"""
This type stub file was generated by pyright.
"""

import os
from .cntk_backend import *
from .theano_backend import *

_BACKEND = "tensorflow"
if "KERAS_BACKEND" in os.environ:
    _backend = os.environ["KERAS_BACKEND"]
    backends = "cntk", "tensorflow", "theano"
    _BACKEND = _backend
if _BACKEND == "cntk":
    ...
else:
    ...
