"""
This type stub file was generated by pyright.
"""

import pycocotools._mask as _mask

__author__ = 'tsungyi'
iou = _mask.iou
merge = _mask.merge
frPyObjects = _mask.frPyObjects
def encode(bimask):
    ...

def decode(rleObjs):
    ...

def area(rleObjs):
    ...

def toBbox(rleObjs):
    ...

