"""
This type stub file was generated by pyright.
"""

from .load_backend import abs, all, any, arange, argmax, argmin, backend, batch_dot, batch_flatten, batch_get_value, batch_normalization, batch_set_value, bias_add, binary_crossentropy, cast, cast_to_floatx, categorical_crossentropy, clear_session, clip, concatenate, constant, control_dependencies, conv1d, conv2d, conv2d_transpose, conv3d, conv3d_transpose, cos, count_params, ctc_batch_cost, ctc_decode, ctc_label_dense_to_sparse, cumprod, cumsum, depthwise_conv2d, dot, dropout, dtype, eager, elu, epsilon, equal, eval, exp, expand_dims, eye, flatten, floatx, foldl, foldr, function, gather, get_session, get_uid, get_value, gradients, greater, greater_equal, hard_sigmoid, identity, image_data_format, in_test_phase, in_top_k, in_train_phase, int_shape, is_keras_tensor, is_placeholder, is_sparse, is_tensor, is_variable, l2_normalize, learning_phase, less, less_equal, local_conv1d, local_conv2d, log, logsumexp, manual_variable_initialization, map_fn, max, maximum, mean, min, minimum, moving_average_update, name_scope, ndim, normalize_batch_in_training, normalize_data_format, not_equal, one_hot, ones, ones_like, pattern_broadcast, permute_dimensions, placeholder, pool2d, pool3d, pow, print_tensor, prod, random_binomial, random_normal, random_normal_variable, random_uniform, random_uniform_variable, relu, repeat, repeat_elements, reset_uids, reshape, resize_images, resize_volumes, reverse, rnn, round, separable_conv1d, separable_conv2d, set_epsilon, set_floatx, set_image_data_format, set_learning_phase, set_session, set_value, shape, sigmoid, sign, sin, size, slice, softmax, softplus, softsign, sparse_categorical_crossentropy, spatial_2d_padding, spatial_3d_padding, sqrt, square, squeeze, stack, std, stop_gradient, sum, switch, symbolic, tanh, temporal_padding, tile, to_dense, transpose, truncated_normal, update, update_add, update_sub, var, variable, zeros, zeros_like

if backend() == 'theano':
    ...
else:
    ...
