"""
This type stub file was generated by pyright.
"""

import keras_applications
from __future__ import absolute_import, division, print_function
from .. import backend, layers, models, utils
from .vgg16 import VGG16
from .vgg19 import VGG19
from .resnet50 import ResNet50
from .inception_v3 import InceptionV3
from .inception_resnet_v2 import InceptionResNetV2
from .xception import Xception
from .mobilenet import MobileNet
from .mobilenet_v2 import MobileNetV2
from .densenet import DenseNet121, DenseNet169, DenseNet201
from .nasnet import NASNetLarge, NASNetMobile
from .resnet import ResNet101, ResNet152
from .resnet_v2 import ResNet101V2, ResNet152V2, ResNet50V2

def keras_modules_injection(base_fun):
    ...

