"""
This type stub file was generated by pyright.
"""

from . import keras_modules_injection

@keras_modules_injection
def DenseNet121(*args, **kwargs):
    ...

@keras_modules_injection
def DenseNet169(*args, **kwargs):
    ...

@keras_modules_injection
def DenseNet201(*args, **kwargs):
    ...

@keras_modules_injection
def decode_predictions(*args, **kwargs):
    ...

@keras_modules_injection
def preprocess_input(*args, **kwargs):
    ...

