"""
This type stub file was generated by pyright.
"""

from . import keras_modules_injection

@keras_modules_injection
def ResNet50V2(*args, **kwargs):
    ...

@keras_modules_injection
def ResNet101V2(*args, **kwargs):
    ...

@keras_modules_injection
def ResNet152V2(*args, **kwargs):
    ...

@keras_modules_injection
def decode_predictions(*args, **kwargs):
    ...

@keras_modules_injection
def preprocess_input(*args, **kwargs):
    ...

