"""
This type stub file was generated by pyright.
"""

import sys
from distutils.core import *
from numpy.distutils.command import bdist_rpm, build, build_clib, build_ext, build_py, build_scripts, build_src, config, config_compiler, install, install_clib, install_data, install_headers, sdist
from typing import Any, Optional

if 'setuptools' in sys.modules:
    have_setuptools = True
else:
    have_setuptools = False
numpy_cmdclass = { 'build': build.build,'build_src': build_src.build_src,'build_scripts': build_scripts.build_scripts,'config_cc': config_compiler.config_cc,'config_fc': config_compiler.config_fc,'config': config.config,'build_ext': build_ext.build_ext,'build_py': build_py.build_py,'build_clib': build_clib.build_clib,'sdist': sdist.sdist,'install_data': install_data.install_data,'install_headers': install_headers.install_headers,'install_clib': install_clib.install_clib,'install': install.install,'bdist_rpm': bdist_rpm.bdist_rpm }
if have_setuptools:
    ...
def _dict_append(d, **kws):
    ...

def _command_line_ok(_cache: Optional[Any] = ...):
    """ Return True if command line does not contain any
    help or display requests.
    """
    ...

def get_distribution(always: bool = ...):
    ...

def setup(**attr):
    ...

def _check_append_library(libraries, item):
    ...

def _check_append_ext_library(libraries, lib_name, build_info):
    ...

