"""
This type stub file was generated by pyright.
"""

from distutils.core import Distribution
from typing import Any, Optional

class NumpyDistribution(Distribution):
    def __init__(self, attrs: Optional[Any] = ...):
        self.scons_data = ...
        self.installed_libraries = ...
        self.installed_pkg_config = ...
    
    def has_scons_scripts(self):
        ...
    


