"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

def configuration(parent_package=..., top_path: Optional[Any] = ...):
    ...

if __name__ == "__main__":
    config = configuration(top_path='').todict()
